name: expense_tracker
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.11.4

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  firebase_core: ^4.6.0
  cloud_firestore: ^6.2.0
  fl_chart: ^1.2.0
  csv: ^5.1.1
  path_provider: ^2.1.5
  permission_handler: ^12.0.1
  firebase_auth: ^6.3.0

dev_dependencies:
  flutter_native_splash: ^2.4.0   # ✅ UPDATED (IMPORTANT)
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

#SPLASH SCREEN Configuration
flutter_native_splash:
  color: "#0D1B2A"
  android: true
  ios: true
  image: assets/logo.png
  android_gravity: center
  ios_content_mode: center

  # 🔥 ANDROID 12 FIX (THIS WAS MISSING)
  android_12:
    image: assets/logo.png
    icon_background_color: "#0D1B2A"

flutter:
  uses-material-design: true

  assets:
    - assets/logo.png